### ISSUE TITLE
Separate functionality into several classes

### ISSUE THREAD

**Issue by brendt** [spatie/dns#1]
Right now, the `DnsInfo` class holds a lot of functionality. I'd prefer two classes to separate their concerns.

These lines are the real logic behind retrieving DNS info, they belong in a separate class: https://github.com/spatie/dns-info/blob/4d9e0aea4bab2c68ef7d8cd177f245fcb33473cc/src/DnsInfo.php#L117-L172

These lines are utility methods, making it easier to use the DNS lookup functionality, they belong in some kind of facade class: https://github.com/spatie/dns-info/blob/4d9e0aea4bab2c68ef7d8cd177f245fcb33473cc/src/DnsInfo.php#L29-L115

**Comment by introwit** [comment]
@freekmurze your thoughts and review of the package? Will refactor together.

**Comment by freekmurze** [comment]
Tbh I'd just lose to helper methods. `getRecords` is easy and flexible enough

**Comment by freekmurze** [comment]
Rewritten the class, this issue is not relevant anymore.
