### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by elmarcomilani** [spatie/dns#12]
Hi!

I've installed this script correctly with Composer but I can't load the class.
Code (run.php):
```
<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require __DIR__ . '/vendor/autoload.php';

$dns = new Spatie\Dns('spatie.be');
```

Error:
```
Fatal error: Uncaught Error: Class 'Spatie\Dns' not found in /var/www/html/spatie/run.php:16 Stack trace: #0 {main} thrown in /var/www/html/spatie/run.php on line 16
```

**Comment by freekmurze** [comment]
Please check your vendor folder to see if the package is there.

**Comment by elmarcomilani** [comment]
Yes, all the packages are there.

![screenshot 21](https://user-images.githubusercontent.com/36673389/36469761-a2b99cb4-16e8-11e8-8cb3-30705341eecd.png)

And inside spatie I have:
spatie
--dns
----src
------Exceptions
--------InvalidArgument.php
------Dns.php
----.stylecy.xml
----CHANGELOG.md
----composer.json
----CONTRIBUTING.md
----LICENSE.md
----README.md

**Comment by freekmurze** [comment]
I tried installing the package in an empty folder on my mac and it just works. Travis seems to be picking it up too. So I guess it's a problem at your end. 

Things to try:
- try installing another package
- try setting it up from scratch again
- reinstall composer

**Comment by reefki** [comment]
I have the same problem `Class 'Spatie\Dns' not found`.

**Comment by freekmurze** [comment]
It seems like there was a wrong example in the readme.

Try using the class `Spatie\Dns\Dns`
