### ISSUE TITLE
Weird issue with dig command on VM

### ISSUE THREAD

**Issue by TonnyORG** [spatie/dns#15]
Hello guys,

So after using your library for a couple weeks, I figured out about a weird behavior exclusive of my VM (Vagrant, Ubuntu) and CNAME records (it doesn't happen with any other record type afaik). As soon as I figured out about the error, I start to play with our friend `var_dump` so I figured out the command that you guys run to fetch for the DNS records and "vardump-ed it".

So if I run this on my host machine (MacOS):
```
dig +nocmd whateverrecord.domain.com CNAME +multiline +noall +answer
```

I get something like this:
```
whateverrecord.domain.com.	293 IN CNAME verify.anotherdomain.com.
```

But if I do run the same command from my VM (vagrant) it doesn't work, it just returns nothing; do you guys think this is an error on any VM in general, on `dig` or what it could be?

In addition, is this something we can solve through the library itself or is a configuration/VM/OS thing?

**Comment by freekmurze** [comment]
Does using `dig` directly work on your VM?

**Comment by TonnyORG** [comment]
For CNAME it doesn't, for other record types it does.

**Comment by freekmurze** [comment]
I'm guessing your problem has nothing to do with our package, but with how `dig` is executed on your VM.

**Comment by TonnyORG** [comment]
Sorry for the late response,

So I guess it is, was trying to figure out if someone else had the same issue running that command on a VM and see if we could fix it (or build something around it to make it work from the package).

Thanks man!
