### ISSUE TITLE
Why is this package?

### ISSUE THREAD

**Issue by v1shky** [spatie/dns#17]
What is wrong with using the PHP function dns_get_record() directly?

**Comment by freekmurze** [comment]
There is nothing wrong with that.

**Comment by oliverpool** [comment]
This package is more flexible, since it allows you to specify the `nameserver`.

However it depends on `dig`.

Some interesting history about this package: https://murze.be/a-beautiful-webapp-to-fetch-dns-records

**Comment by v1shky** [comment]
I was convinced already but thanks @oliverpool for the information 👍
