### ISSUE TITLE
Don't use array indices to lookup record types

### ISSUE THREAD

**Issue by brendt** [spatie/dns#2]
By reading this code, I cannot actually tell which type of record is `5`: https://github.com/spatie/dns-info/blob/4d9e0aea4bab2c68ef7d8cd177f245fcb33473cc/src/DnsInfo.php#L102-L105

I think the record type belong in an enum class, something like this:

```php
class RecordType 
{
    const A = 'A';
    const AAAA = 'AAAA';
    const NS = 'NS';
    // ...
}
```

This makes the following code a lot more readable:

```php
$this->retrieveDnsRecords(RecordType::TXT);
```

Furthermore, it's never good to give array indices more meaning than just a "position in that array". Because after all, that's the only thing an array index really means. If you're seeing more meaning to an index than just that, chances are there a better way to store that data structure than an array.

**Comment by freekmurze** [comment]
```
$this->retrieveDnsRecords(RecordType::TXT);
```

That good advice. We could then also lose the dedicated `getTXTRecords` and related functions. 

The above `retrieveDnsRecords` is easy enough to use. Make it accept an array of strings too.

**Comment by introwit** [comment]
- Pushed the refactor commit: 7b560511420bb0f14547bb6a5ba4eb42af88601a

@brendt Now array is used for what it should be :) @freekmurze Refactored and now it can be used as follows:

```php
$dns = new Spatie\Dns('spatie.be');
echo $dns->getARecords();
echo $dns->getTxtRecords();
echo $dns->getRecords('A');
echo $dns->getRecords(['A', 'TXT']);
echo $dns->getAllRecords(); // To get all records
```
