### ISSUE TITLE
Output into array

### ISSUE THREAD

**Issue by Tliabo** [spatie/dns#22]
At the time the output of a record are just Strings. 

like this:
> array (size=1)
>   0 => string 'example.com.		3600 IN	SOA ns.example.com. host.example.com. (
> 				2018073194 ; serial
> 				10800      ; refresh (3 hours)
> 				3600       ; retry (1 hour)
> 				605800     ; expire (1 week 16 minutes 40 seconds)
> 				3600       ; minimum (1 hour)
> 				)
> ' (length=260)

Wouldnt it be more confortable if the output would be in arrays?

It is not beautiful but
My output at the time looks like this:

> 0 => string 'example.com.' (length=12)
>   1 => string '3600' (length=4)
>   2 => string 'IN' (length=2)
>   3 => string 'SOA' (length=3)
>   4 => string 'ns.example.com.' (length=19)
>   5 => string 'host.example.com.' (length=25)
>   6 => string '(' (length=1)
>   7 => string '2018073194' (length=10)
>   8 => string ';' (length=1)
>   9 => string 'serial' (length=6)
>   10 => string '10800' (length=5)
>   11 => string ';' (length=1)
>   12 => string 'refresh' (length=7)
>   13 => string '(3' (length=2)
>   14 => string 'hours)' (length=6)
>   15 => string '3600' (length=4)
>   16 => string ';' (length=1)
>   17 => string 'retry' (length=5)
>   18 => string '(1' (length=2)
>   19 => string 'hour)' (length=5)
>   20 => string '605800' (length=6)
>   21 => string ';' (length=1)
>   22 => string 'expire' (length=6)
>   23 => string '(1' (length=2)
>   24 => string 'week' (length=4)
>   25 => string '16' (length=2)
>   26 => string 'minutes' (length=7)
>   27 => string '40' (length=2)
>   28 => string 'seconds)' (length=8)
>   29 => string '3600' (length=4)
>   30 => string ';' (length=1)
>   31 => string 'minimum' (length=7)
>   32 => string '(1' (length=2)
>   33 => string 'hour)' (length=5)
>   34 => string ')' (length=1)
>   35 => string '' (length=0)

**Comment by freekmurze** [comment]
For our projects the output is good enough. Feel free to send a PR with tests for new functionality.
