### ISSUE TITLE
Dig command failed with message: `sh: 1: dig: not found ubuntu 16.04

### ISSUE THREAD

**Issue by shahzadthathal** [spatie/dns#24]
I have dig command installed on my ubuntu 16.04 but your dns code doesn't work and display error:

```
{
    "message": "Dig command failed with message: `sh: 1: dig: not found`",
    "exception": "Spatie\\Dns\\Exceptions\\CouldNotFetchDns",
    "file": "/var/www/vendor/spatie/dns/src/Exceptions/CouldNotFetchDns.php",
```
Dig at my laptop has this version:

```
shahzad@shahzad:~$ dig

; <<>> DiG 9.10.3-P4-Ubuntu <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46396
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 27

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;.			
```

Any idea what is wrong here?

**Comment by shahzadthathal** [comment]
I forgot to mentions this issues is within the docker php-fpm container.

**Comment by typoworx-de** [comment]
You must install dig in the docker container if missing. If docker is running on ubuntu use:
> apt-get install dnsutils

If the docker uses some kind of non-package managed linux you also can try to copy dig manually inside docker. use
> which dig
> ldd /usr/bin/dig
then copy dig binary and all (missing) libraries into docker f.e. using
> docker cp (the given files) (docker instance name:path)

Also check if php is allowed to execute shell-commands.
