### ISSUE TITLE
MacOS issue

### ISSUE THREAD

**Issue by code2prog** [spatie/dns#26]
Package not work on MacOS local environment:
Dig command failed with message: `` {"exception":"[object] (Spatie\\Dns\\Exceptions\\CouldNotFetchDns(code: 0): Dig command failed with message: ``

I use Valet Plus on local env. dig command is available when i use dig from command line and  works just fine

**Comment by freekmurze** [comment]
Make sure you have dig installed and that php has the right permission to call it.
