### ISSUE TITLE
Empty Array

### ISSUE THREAD

**Issue by ServerJunge** [spatie/dns#31]
Hi,

I try to use the package on Windows and installed dig. dig is working fine, but when I run 

`$dns = new Dns('spatie.be');`

I get back the following array.

````
Dns {#214 ▼
  #domain: "spatie.be"
  #nameserver: ""
  #recordTypes: array:11 [▼
    0 => "A"
    1 => "AAAA"
    2 => "CNAME"
    3 => "NS"
    4 => "SOA"
    5 => "MX"
    6 => "SRV"
    7 => "TXT"
    8 => "DNSKEY"
    9 => "CAA"
    10 => "NAPTR"
  ]
}
````
Any idea?

**Comment by freekmurze** [comment]
We don't use Windows, so can't help you here. If you find that our package does something wrong, feel free to PR a fix.
