### ISSUE TITLE
Cached DNS records

### ISSUE THREAD

**Issue by onassar** [spatie/dns#32]
I'm trying to ensure I get _all_ the DNS records each time I make a call; can this be forced through `dig` using your library?

**Comment by freekmurze** [comment]
This is how you can get all records

$dns = new Spatie\Dns\Dns('spatie.be');

$dns->getRecords(); // returns all available dns records

**Comment by onassar** [comment]
Hmm; it's not.
For example, I run the domain getstencil.com and know exactly which `CNAME` and `TXT` records it has.

When I run your library against that host, I get this:
![](https://i.imgur.com/VCzPxDM.png)

Lots of records are missing.

**Comment by freekmurze** [comment]
That seems like a good result to me. Keep in mind that we can't automatically give you dns records for all subdomains and for certain record types.

Which records are missing?

**Comment by onassar** [comment]
The host has a number of `mx` records and `txt` records which aren't showing up?

**Comment by freekmurze** [comment]
Can you get to these records when using `dig` directly?

**Comment by onassar** [comment]
Haven't tried
