### ISSUE TITLE
Is it possible to test for SERVFAIL?

### ISSUE THREAD

**Issue by roelvanduijnhoven** [spatie/dns#42]
I have an instance where DIG will return a SERVFAIL. But whereas this library will give an empty array as a result.

This is relevant in the context of LetsEncrypt. If a server responds to a CAA DNS query with `SERVFAIL` it will _not_ accept that. For my purposes I want to detect myself if this is the case, before issuing a command to LetsEncrypt.

I searched the repo op SERVFAIL and did not found a hit, so I guess this is not supported. Is it possible to implement this? If so: any hints as how to do so? I would be willing to implement it!

**Comment by freekmurze** [comment]
I don't have any experience with this, so you'll have to figure this out by yourself.

I the code is simple, I'd accept a PR with tests that adds this to the package.

**Comment by roelvanduijnhoven** [comment]
Thanks for your reply @freekmurze.

In order for this to work we should turn on the comments (`+comments`). And then parse the following line:

> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36493

The following statuses could be returned:

> - **NOERROR** - Everything's cool. The zone is being served from the requested authority without issues.
> - **SERVFAIL** - The name that was queried exists, but there's no data or invalid data for that name at the requested authority. 
> - **NXDOMAIN** - The name in question does not exist, and therefore there is no authoritative DNS data to be served.
> - **REFUSED** - Not only does the zone not exist at the requested authority, but their infrastructure is not in the business of serving things that don't exist at all.
> -- https://ns1.com/blog/decoding-dig-output#mainContent

We can emit a different exception for `SERVFAIL` and `REFUSED`. Both exceptions could be subclasses of `CouldNotFetchDns`. The `NXDOMAIN` and `NOERROR` are fine. 

The test suite does not use mocking. So in order for me to test this, there would need to be a hostname that will return a SERVFAIL, REFUSED and NXDOMAIN error. **That _would_ require some work on your end @freekmurze I'm afraid**.

Apart from that, implementing this would not be difficult and hardly increase complexity I think.
