### ISSUE TITLE
Issue with domain

### ISSUE THREAD

**Issue by andresledo** [spatie/dns#44]
Hello,
First, thank you for your work.

I am trying to implement this on a website, but I have found that with some domains it does not work. For example with "luna.info".

```
$dns = new Spatie\Dns\Dns('luna.info');
$dnsRecords = $dns->getRecords();
dd($dnsRecords);
```

The result returns an empty string while https://dnsrecords.io/luna.info works correctly on your site.

What am I doing wrong?

**Comment by remotelyliving** [comment]
@andresledo just flying by and looking at open issues here. I do not work on or maintain this project, but it might be your nameserver. Try instantiating the dns resolver with a different nameserver like so `$dns = new Spatie\Dns\Dns('spatie.be', 'ns1.openminds.be'); // use ns1.openminds.be`

But it looks like whoever setup luna.info has some serious DNS configuration issues on their end. Cloudflare / GoogleDNS / dig do not show any records for it.

https://toolbox.googleapps.com/apps/dig/#A/

It always helps troubleshoot when you try and get a consensus between nameservers as DNS is *eventually* consistent and by eventually I mean 72 hours lag time hehe.

I ended up creating a library that uses this resolver and a few others to determine consensus results. Definitely no fun trying to figure it out from one source.
