### ISSUE TITLE
Clashing symfony/process

### ISSUE THREAD

**Issue by emotality** [spatie/dns#45]
Hi Spatie 👋 

I'm don't have PHP 7.4 so I want to use `spatie/dns:1.4.2` but it is using `symfony/process:^4.0` and is clashing with Horizon's `symfony/process:^5.0`.

Any solution except upgrading to PHP 7.4?

Or is upgrading from PHP 7.2 to 7.4 fine? What could break?

Thanks! ✌️

**Comment by freekmurze** [comment]
Please upgrade to PHP 7.4

We can’t predict what will break in your environment, but probably you’ll only run into minor, easily fixable errors.
