### ISSUE TITLE
Add support for PHP 7.2.5 and 7.3

### ISSUE THREAD

**Issue by aredev** [spatie/dns#46]
Hi Spatie,

We are using this package in one of our applications and have recently upgraded to Laravel 7. During one of our deployment tests, we noticed a failure due to incompatibility of this package since it only supports PHP7.4. We agree that we should always use the latest PHP version. However, our application is deployed within Elastic Beanstalk and this does not support PHP7.4. 

Therefore, we kindly request to add temporary support for PHP7.2.5 and 7.3, since this is also the minimum requirements of Laravel 7 and Symfony 5.

Hope to hear from you!

**Comment by freekmurze** [comment]
We don't have a need for PHP 7.2 and 7.3 anymore so we are not going to invest our time in it. 

Please fork the package and use that. Switch back to this one when you can use PHP 7.4.
