### ISSUE TITLE
How to use correctly?

### ISSUE THREAD

**Issue by MrMooky** [spatie/dns#48]
I was wondering how the output is supposed to be handled. When I `dd($dns->getRecords('CNAME'))` a domain, I get this result:

`"test.my-domain.de.\t993 IN CNAME vimahi-yazazo.some-domain.com.\n"`

I'm only interested in the actual value `vimahi-yazazo.some-domain.com`. Since this is a string, I tried to `explode(' ', $dns->getRecords('CNAME'))` but then I would need to use key[2] to fetch the value, but still have `.\n` at the end.

I know you guys use this in your own projects, so I was just wondering how. How would I be able to get a clean result without doing multiple PHP rounds?

**Comment by freekmurze** [comment]
We actually only use this on our dns site and do not do any formatting of the results afterwards. 

So I guess you'll have to do some regex fu to get what you want.
