### ISSUE TITLE
Can we get json value?

### ISSUE THREAD

**Issue by lovecoding-git** [spatie/dns#51]
![image](https://user-images.githubusercontent.com/61916777/92158379-63632580-ee5e-11ea-90c7-3fc97233132e.png)

This is value when I was going to get A record using package.

```
$dns = new \Spatie\Dns\Dns($domain);
return $dns->getRecords('A);
```

Can I get only A record value as JSON? or am I missing something?

**Comment by freekmurze** [comment]
There are some examples mentioned in the readme. If you are missing something specific, I'd accept a PR for smallish things.

**Comment by lovecoding-git** [comment]
Hi @freekmurze ,
Would you please let me know how it should be like?
```
$dns = new \Spatie\Dns\Dns($domain);
return $dns->getRecords('A');
```
Above result should be just like this? 
`138.197.187.74`

**Comment by freekmurze** [comment]
No, you'll get the entire record. If you need just that value, create a PR.

**Comment by lovecoding-git** [comment]
Okay,
So the above my result screenshot is correct?
Or it should be displayed as array or JSON?
I am just thinking  if my screenshot result is correct, how I can extract only A record value from above result string.
Probably should I do using string operations?

**Comment by sitenzo** [comment]
> Okay,
> So the above my result screenshot is correct?
> Or it should be displayed as array or JSON?
> I am just thinking if my screenshot result is correct, how I can extract only A record value from above result string.
> Probably should I do using string operations?

Hello @lovecoding-git 
You can use below code to get First IP from A records.

        $Dns = new Spatie\Dns\Dns($this->Url);
        $A = $Dns->getRecords('A');

        $re = '/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/';

        preg_match($re, $A, $matches, PREG_OFFSET_CAPTURE, 0);

        return $matches[0][0];
