### ISSUE TITLE
Cannot use object of type Spatie\Dns\Support\Collection as array

### ISSUE THREAD

**Issue by lucaros97** [spatie/dns#61]
Hi,
Following the docs I tried to get DNS results as following and as written in the docs:

```php
$dns = new Dns();
$records = $dns->getRecords('spatie.be')[0];
```

But this simply returns this:
```
Cannot use object of type Spatie\Dns\Support\Collection as array
```

Also tried to loop through results from this one:
```php
$records = $dns->getRecords('spatie.be');
```

But it's not looping.

How can i loop through results and read them?

**Comment by freekmurze** [comment]
Hi,

In v2.0.1 `getRecords` will return an array, and your code above will behave as expected.

**Comment by lucaros97** [comment]
Hi @freekmurze 
Thanks for the update.

Still can't iterate through the array, now if I try to access property of the array it returns me this:
```
Cannot access protected property Spatie\Dns\Records\A::$type
```

Didn't find where's the problem in the class anyway

**Comment by freekmurze** [comment]
You can use various methods to retrieve info of a record.

```php
$records = $dns->getRecords('spatie.be')

$hostNameOfFirstRecord = $records[0]->host();
```
